name: Build UWP Application

on:
  push:
    branches:
      - master
    paths:
      - "src/**/*"
      - ".github/workflows/main_uwp.yml"
      
env:
  TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
  TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}

jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3
      with:
        msbuild-architecture: x64
      
    - name: NuGet Restore - Platform Project
      run: nuget restore src\FacebookDataExplorer.sln -ConfigFile src\nuget.config 
    
    - name: Build UWP Project
      run: msbuild src\FacebookDataExplorer.sln /p:Platform=x64 /p:Configuration=Debug /p:AppxPackageSigningEnabled=false /p:UapAppxPackageBuildMode=CI /p:AppxBundle=Never /p:AppxPackageSigningEnabled=false
    
